### ISSUE TITLE
Why no one is using the funds in opencollective?

### ISSUE THREAD

**Issue by albacoretuna** [rspec/rspec-metagem#40]
Hello, 
I'm looking for projects to sponsor on OpenCollective for my employer and we use rspec a lot. 

I checked the [opencollective page](https://opencollective.com/rspec) and seems like there's about 5000 usds collected but no one has ever used it. 
Is there any plans for it? Because we'd rather help a project that actually uses the funds to improve the library.

**Comment by JonRowe** [comment]
Hi @albacoretuna 

We were gifted the initial funds by Coinbase who generously donated 5000 USD if we signed up to open collective. The feeling of the team at the time was that it would be useful for paying our minimal infrastructure costs (domain name mostly) and for improving our documentation by engaging a technical writer. We haven't had any bills to pay since then and we've just lacked the momentum for engaging a writer, but I'm still very much in favour of using the funds to this end.

**Comment by albacoretuna** [comment]
Better documentation sounds good. Thanks.
