### ISSUE TITLE
Document the fact that lets run in parallel, and let!s (apparently) do not

### ISSUE THREAD

**Issue by buzzware** [rspec/rspec-metagem#55]
I've been going crazy trying to understand why these rspecs fail randomly.
There are active models each created in a let, and then interdependencies between the lets.
Firstly, I haven't seen any documentation to say that lets are executed in parallel on multiple threads (they seem to be). This fact can be very important to realise.
Secondly, its not explicitly stated that (I assume) let!s are run serially as a result of being put together into a before hook. If they are not, there needs to be a way to specify lets that are executed single threaded serially.
config.threadsafe I think is a different thing - it makes each let threadsafe individually, but still allows two lets to execute in parallel.

**Comment by pirj** [comment]
The problem you are experiencing might relate to `rspec-core` or `rspec-rails`, or Rails.
However, it's hard to determine without a reproduction example, can you please provide one?

What makes you think it's running in parallel or in different threads?

**Comment by JonRowe** [comment]
RSpec itself does not run parallel, it was built for MRI and the GIL, and whilst there are plans to have an inbuilt parallel runner, we haven't got there yet. So any parallel usage is from a 3rd party (and thus unsupported by us) or your own code. However we will try to help here. 

Firstly, understand that `let` is a syntactic sugar for roughly: `define_method(name) { @@__value__ ||= block.call }` so it defines a method in your example class, it has no direct knowledge of the thread you are running in, nor does it need to. Now because class variables are not thread-safe, when you turn on thread-safe mode we use a re-entrant mutex to write to this variable, this is the only difference, it prevents two threads defining a let simultaneously.

It will not stop another let running in another thread ("executed in parallel" as you have said, however there is no such thing, a normal `let` is run when the method is called (as it's just a method)) so if you have inter-dependant lets and you have multiple threads calling them you will see the let definitions run, but the inter-dependant call will block until the first is complete, then return the value.

Secondly, `let!` is a short cut for `let(name) {}; before { name }` which is documented as:

>  Just like `let`, except the block is invoked by an implicit `before` hook. This serves a dual purpose of setting up state and providing a memoized reference to that state.

As RSpec doesn't do anything in parallel, we don't specifically say "serially" because everything in RSpec is serial.

**Comment by buzzware** [comment]
Thankyou to both of you, especially the indepth explanation @JonRowe.
While I haven't got the whole test suite (that I didn't write) passing reliably yet, I think part of the explanation for the erratic behaviour is faulty cleaning of the database because before(:all) is outside the test transaction and perhaps even the Jetbrains debugger misbehaving.
I think I've solved the cleaning issue with double transactions so that before(:all) is well behaved, like this http://renderedtext.com/blog/2012/10/10/cleaning-up-after-before-all-blocks/
Good to hear that rspec doesn't fire threads itself. I don't think the codebase is firing any either, I may have made an incorrect presumption that threading was the issue.

Lastly, the specs often create an activerecord models inside a let, and then may call dependent lets to get models to create associations. Would you regard that as reasonable practice?

**Comment by pirj** [comment]
>  specs often create an activerecord models inside a let, and then may call dependent lets to get models to create associations. Would you regard that as reasonable practice?

Absolutely.

You are always welcome!
Please feel free to reopen this or a issue in `rspec-core`/`rspec-rails` if you feel that RSpec is somehow misbehaving in your setup.

**Comment by pirj** [comment]
As a side note, I wouldn't recommend `:truncation` strategy, it's known to be slow especially on large DB schemas.
You may take a look at [`before_all`/`let_it_be`](https://github.com/palkan/test-prof) instead if your intention is to create models that are later reused by several examples. Beware of the [shared state modification though](https://github.com/palkan/test-prof/pull/178), those considerations not only apply to `let_it_be`, but also for your current use case.

**Comment by pirj** [comment]
For future readers, `before(:context)` behavior with transactions is covered in [this doc](https://relishapp.com/rspec/rspec-rails/docs/transactions).
