### ISSUE TITLE
https://relishapp.com/rspec shows application error

### ISSUE THREAD

**Issue by JunichiIto** [rspec/rspec-metagem#71]
Currently https://relishapp.com/rspec shows application error.

<img width="601" alt="Screenshot 2023-02-28 at 8 37 38" src="https://user-images.githubusercontent.com/1148320/221713981-c08d0321-85a0-4fe4-8fce-a3cc914b7949.png">

Could you investigate it?

Related issue: https://github.com/rspec/rspec-metagem/issues/70 , https://github.com/rspec/doc-site/issues/5

**Comment by JonRowe** [comment]
👋 There is an issue with [relishapp](https://relishapp.com/) at the moment, you can find our website at https://rspec.info which has our API documentation, or read the cucumber scenarios directly from repos.

See: https://github.com/rspec/doc-site/issues/5#issuecomment-1446152910

Closing because this is not an rspec issue.
